### ISSUE TITLE
Side-effect: installs redis

### ISSUE THREAD

**Issue by bbaassssiiee** [mamercad/ansible-sensu-server#3]

**Comment by mamercad** [comment]
It's a prerequisite: https://sensuapp.org/docs/0.25/installation/installation-prerequisites.html

**Comment by bbaassssiiee** [comment]
Such prerequisites can be expressed in meta/main.yml as dependencies. If you create separate roles for those then they are pulled in automatically, it is more elegant, the "one task, one role" mantra.
